"""Chart specification models - visual evidence representations."""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum


class ChartType(str, Enum):
    """Supported chart types."""
    LINE = "line"
    BAR = "bar"
    AREA = "area"
    SCATTER = "scatter"


class AxisConfig(BaseModel):
    """Configuration for chart axis."""
    field: str
    label: str
    format: Optional[str] = None  # "currency", "percentage", "number", "date"
    scale: Optional[str] = None  # "linear", "log"


class Series(BaseModel):
    """Data series for chart."""
    name: str
    data: List[Dict[str, Any]]
    color: str
    style: Optional[str] = None  # "solid", "dashed", "dotted"
    marker: Optional[str] = None  # "circle", "square", "triangle"
    line_width: Optional[int] = 2


class AnnotationType(str, Enum):
    """Types of chart annotations."""
    THRESHOLD = "threshold"
    ANOMALY = "anomaly"
    REFERENCE_LINE = "reference_line"
    LABEL = "label"


class Annotation(BaseModel):
    """Chart annotation for highlighting key points."""
    type: AnnotationType
    value: Optional[float] = None
    points: Optional[List[Dict[str, Any]]] = None
    label: Optional[str] = None
    color: str = "#FF0000"
    style: Optional[str] = "dashed"


class ChartSpec(BaseModel):
    """
    Complete chart specification.

    This is generated by the Chart Builder and consumed by the frontend.
    """
    chart_id: str
    chart_type: ChartType
    title: str
    subtitle: Optional[str] = None
    x_axis: AxisConfig
    y_axis: AxisConfig
    series: List[Series]
    annotations: List[Annotation] = []

    # Display options
    show_legend: bool = True
    show_grid: bool = True
    height: Optional[int] = 400
    width: Optional[int] = None  # Auto if None

    def get_series_by_name(self, name: str) -> Optional[Series]:
        """Get series by name."""
        for s in self.series:
            if s.name == name:
                return s
        return None

    def add_annotation(self, annotation: Annotation):
        """Add an annotation to the chart."""
        self.annotations.append(annotation)

    def has_annotations(self) -> bool:
        """Check if chart has any annotations."""
        return len(self.annotations) > 0

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "chart_id": self.chart_id,
            "chart_type": self.chart_type.value,
            "title": self.title,
            "subtitle": self.subtitle,
            "x_axis": {
                "field": self.x_axis.field,
                "label": self.x_axis.label,
                "format": self.x_axis.format,
                "scale": self.x_axis.scale,
            },
            "y_axis": {
                "field": self.y_axis.field,
                "label": self.y_axis.label,
                "format": self.y_axis.format,
                "scale": self.y_axis.scale,
            },
            "series": [
                {
                    "name": s.name,
                    "data": s.data,
                    "color": s.color,
                    "style": s.style,
                    "marker": s.marker,
                    "line_width": s.line_width,
                }
                for s in self.series
            ],
            "annotations": [
                {
                    "type": a.type.value,
                    "value": a.value,
                    "points": a.points,
                    "label": a.label,
                    "color": a.color,
                    "style": a.style,
                }
                for a in self.annotations
            ],
            "show_legend": self.show_legend,
            "show_grid": self.show_grid,
            "height": self.height,
            "width": self.width,
        }


class ChartBuilder:
    """Helper class for building common chart types."""

    @staticmethod
    def create_trend_chart(
        chart_id: str,
        title: str,
        metric_name: str,
        current_data: List[Dict[str, Any]],
        baseline_data: Optional[List[Dict[str, Any]]] = None,
        anomaly_points: Optional[List[Dict[str, Any]]] = None,
    ) -> ChartSpec:
        """Create a primary trend chart."""
        series = [
            Series(
                name="Current Period",
                data=current_data,
                color="#1f77b4",
                style="solid",
                line_width=3,
            )
        ]

        if baseline_data:
            series.append(
                Series(
                    name="Baseline Period",
                    data=baseline_data,
                    color="#aaaaaa",
                    style="dashed",
                    line_width=2,
                )
            )

        annotations = []
        if anomaly_points:
            annotations.append(
                Annotation(
                    type=AnnotationType.ANOMALY,
                    points=anomaly_points,
                    label="Anomaly",
                    color="#ff0000",
                )
            )

        return ChartSpec(
            chart_id=chart_id,
            chart_type=ChartType.LINE,
            title=title,
            subtitle=f"{metric_name} over time",
            x_axis=AxisConfig(field="date", label="Date", format="date"),
            y_axis=AxisConfig(field="value", label=metric_name, format="number"),
            series=series,
            annotations=annotations,
        )

    @staticmethod
    def create_driver_impact_chart(
        chart_id: str,
        title: str,
        driver_data: List[Dict[str, Any]],
        metric_name: str = "Impact",
    ) -> ChartSpec:
        """Create a driver impact bar chart."""
        return ChartSpec(
            chart_id=chart_id,
            chart_type=ChartType.BAR,
            title=title,
            subtitle="Top contributing drivers ranked by impact",
            x_axis=AxisConfig(field="driver", label="Driver"),
            y_axis=AxisConfig(field="impact", label=metric_name, format="number"),
            series=[
                Series(
                    name="Impact",
                    data=driver_data,
                    color="#2ca02c",
                )
            ],
            show_legend=False,
        )
